name: Deploy React
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code
        uses: actions/checkout@v4      
      - name: Install Node v22 
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install
        run: npm install
      - name: Build static files
        run: npm run build        
  test:
    needs: build    
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: npm run test
  deploy:
    # Add a dependency to the build job
    needs: test
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}      
    runs-on: ubuntu-latest
    # Deploy to the github-pages environment
    steps:
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 
        with:
          path: build/  
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 